Vagrant.configure(2) do |config|
    config.vm.box = "bento/ubuntu-20.04-arm64"
  
    config.vm.define "mbrettscS" do |control|
      control.vm.hostname = "mbrettscS"
      control.vm.network "private_network", ip: "192.168.56.110"
      config.vm.provision "file", source: "./confs/", destination: "$HOME/"

      control.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "512"
        v.vmx["numvcpus"] = "1"
      end
      control.vm.provision "shell", "path" => "./scripts/script.sh"
    end
end
